<a href="https://colab.research.google.com/github/ANG29/COMP5318/blob/main/comp5381_a1_test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import scipy.io
import numpy as np 

In [3]:
file_balanced = "/content/drive/MyDrive/COMP5318/emnist-balanced.mat"
file_by_class = "/content/drive/MyDrive/COMP5318/emnist-byclass.mat"
file_by_merge = "/content/drive/MyDrive/COMP5318/emnist-bymerge.mat"

In [4]:
scipy.io.loadmat(file_balanced, mdict=None, appendmat=True)

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Dec 20 07:38:25 2016',
 '__version__': '1.0',
 'dataset': array([[(array([[(array([[0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0],
                        ...,
                        [0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[45],
                        [36],
                        [43],
                        ...,
                        [23],
                        [31],
                        [ 8]], dtype=uint8), array([[ 493],
                        [1020],
                        [2358],
                        ...,
                        [ 515],
                        [ 137],
                        [3534]], dtype=uint16))                             ]],
               dtype=[('images', 'O'), ('labels', '

In [5]:
scipy.io.loadmat(file_by_class, mdict=None, appendmat=True)

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun Dec 18 07:27:57 2016',
 '__version__': '1.0',
 'dataset': array([[(array([[(array([[0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0],
                        ...,
                        [0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0],
                        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[35],
                        [36],
                        [ 6],
                        ...,
                        [ 5],
                        [11],
                        [22]], dtype=uint8), array([[2376],
                        [3994],
                        [3699],
                        ...,
                        [  26],
                        [ 421],
                        [1243]], dtype=uint16))                             ]],
               dtype=[('images', 'O'), ('labels', '

In [6]:
mat_data_by_merge = scipy.io.loadmat(file_by_merge, mdict=None, appendmat=True)

In [7]:
mat_data_by_merge["dataset"]

array([[(array([[(array([[0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       ...,
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[24],
                       [36],
                       [ 5],
                       ...,
                       [ 9],
                       [36],
                       [ 1]], dtype=uint8), array([[  33],
                       [3568],
                       [3100],
                       ...,
                       [3406],
                       [ 466],
                       [ 189]], dtype=uint16))                             ]],
              dtype=[('images', 'O'), ('labels', 'O'), ('writers', 'O')]), array([[(array([[0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
                       [0, 0, 0, ..., 0, 0, 0],
        

In [8]:
data_train_by_merge = mat_data_by_merge["dataset"][0][0][0][0][0][0]

In [9]:
data_train_by_merge.shape

(697932, 784)

In [10]:
label_train_by_merge = mat_data_by_merge["dataset"][0][0][0][0][0][1]

In [11]:
label_train_by_merge

array([[24],
       [36],
       [ 5],
       ...,
       [ 9],
       [36],
       [ 1]], dtype=uint8)

In [12]:
data_test_by_merge = mat_data_by_merge["dataset"][0][0][1][0][0][0]

In [13]:
data_test_by_merge.shape

(116323, 784)

In [14]:
lable_test_by_merge = mat_data_by_merge["dataset"][0][0][1][0][0][1]

In [15]:
lable_test_by_merge

array([[24],
       [22],
       [28],
       ...,
       [ 3],
       [ 3],
       [ 7]], dtype=uint8)

In [16]:
mapping = mat_data_by_merge["dataset"][0][0][2]

In [17]:
mapping

array([[  0,  48],
       [  1,  49],
       [  2,  50],
       [  3,  51],
       [  4,  52],
       [  5,  53],
       [  6,  54],
       [  7,  55],
       [  8,  56],
       [  9,  57],
       [ 10,  65],
       [ 11,  66],
       [ 12,  67],
       [ 13,  68],
       [ 14,  69],
       [ 15,  70],
       [ 16,  71],
       [ 17,  72],
       [ 18,  73],
       [ 19,  74],
       [ 20,  75],
       [ 21,  76],
       [ 22,  77],
       [ 23,  78],
       [ 24,  79],
       [ 25,  80],
       [ 26,  81],
       [ 27,  82],
       [ 28,  83],
       [ 29,  84],
       [ 30,  85],
       [ 31,  86],
       [ 32,  87],
       [ 33,  88],
       [ 34,  89],
       [ 35,  90],
       [ 36,  97],
       [ 37,  98],
       [ 38, 100],
       [ 39, 101],
       [ 40, 102],
       [ 41, 103],
       [ 42, 104],
       [ 43, 110],
       [ 44, 113],
       [ 45, 114],
       [ 46, 116]], dtype=uint8)

In [18]:
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch
import torchvision
import torchvision.transforms as transforms

In [19]:
torch.from_numpy(data_test_by_merge)

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8)

# 开始卷

In [20]:
data_train_by_merge = data_train_by_merge/255


In [21]:
import numpy as np
pic_list = []
for pic in data_train_by_merge:
  new_pic = np.array(pic).reshape(28,28)
  pic_list.append(new_pic)



In [ ]:
data_train_by_merge_28 = np.array(pic_list)

In [ ]:
data_train_torch = torch.from_numpy(data_train_by_merge_28)

In [ ]:
trainloader = torch.utils.data.DataLoader(data_train_torch, batch_size=4,
	shuffle=True, num_workers=2)

In [ ]:
trainloader

In [ ]:
tmp_list = []
for i in mapping:
  tmp_list.append(i[0])
classes = tuple(tmp_list)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# 显示图片的函数


def imshow(img):
  #img = img / 2 + 0.5     #  [-1,1] -> [0,1]
  npimg = img.numpy()
  plt.imshow(np.transpose(npimg, (1, 2, 0))) # (channel, width, height) -> (width, height, channel)


# 随机选择一些图片
dataiter = iter(trainloader)
images = dataiter.next()

# 显示图片
imshow(torchvision.utils.make_grid(images))
# 打印label
#print(' '.join('%5s' % classes[labels[j]] for j in range(4)))

In [ ]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
	def __init__(self):
		super(Net, self).__init__()
		self.conv1 = nn.Conv2d(1, 6, 5)
		self.pool = nn.MaxPool2d(2, 2)
		self.conv2 = nn.Conv2d(6, 16, 5)
		self.fc1 = nn.Linear(16 * 5 * 5, 120)
		self.fc2 = nn.Linear(120, 84)
		self.fc3 = nn.Linear(84, 10)
	
	def forward(self, x):
		x = self.pool(F.relu(self.conv1(x)))
		x = self.pool(F.relu(self.conv2(x)))
		x = x.view(-1, 16 * 5 * 5)
		x = F.relu(self.fc1(x))
		x = F.relu(self.fc2(x))
		x = self.fc3(x)
		return x

net = Net()

In [ ]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [ ]:
for epoch in range(2):  # 这里只迭代2个epoch，实际应该进行更多次训练 

	running_loss = 0.0
	for i, data in enumerate(trainloader, 0):
		# 得到输入
		inputs, labels = data
		
		# 梯度清零 
		optimizer.zero_grad()
		
		# forward + backward + optimize
		outputs = net(inputs)
		loss = criterion(outputs, labels)
		loss.backward()
		optimizer.step()
		
		# 定义统计信息
		running_loss += loss.item()
		if i % 2000 == 1999:
			print('[%d, %5d] loss: %.3f' %
				(epoch + 1, i + 1, running_loss / 2000))
		running_loss = 0.0

print('Finished Training')

In [ ]:
dataiter = iter(testloader)
images, labels = dataiter.next()


imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))